### ISSUE TITLE
UTF-8 Encoding Issue

### ISSUE THREAD

**Issue by tomgco** [tomgco/gzippo#4]
It seems that Gzipping certain utf-8 characters using node-compress causes them not to display correctly.

**Comment by tomgco** [comment]
Fixed in gzippo 0.0.3

**Comment by boris-felix** [comment]
Hi. Im on gzippo 0.0.5 and still have the bug. Encoded characters appeas like diamond.

**Comment by tomgco** [comment]
Can you provide the utf-8 string you are using?

**Comment by boris-felix** [comment]
We make i18n by putting our wordings in the JS. This is an exemple : 'Tous les épisodes'.

**Comment by boris-felix** [comment]
Hi tom ! Have you include your last commit in a release ? We are very interested about it and this is a very important problem we have to resolve on our side. We are waiting for your answer. Thank you.

**Comment by tomgco** [comment]
Hi, 

Yes it has been fixed in the latest release 0.0.6. I just never got round to closing this issue, hope this is now working for you!

**Comment by boris-felix** [comment]
Thanks a lot ! its work !
